name: crypto-laravel
services:
    web:
        depends_on:
            - database
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_DISMOD=xdebug
        ports:
            - ${APP_PORT}:80
        restart: unless-stopped
        image: webdevops/php-apache-dev:8.3
    database:
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        image: postgres
        ports:
            - ${DB_PORT}:5432
        restart: unless-stopped
        volumes:
            - database:/var/lib/postgresql/data
volumes:
    database:
        driver: local
